import Head from "next/head";
import styled, { css } from "styled-components";

import Image from "next/image";

interface CssProps {
  width?: string;
}

export default function Education() {
  return (
    <>
      <Head>
        <title>Education</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <ContentLayout>
          <ProfileBox>
            <ImageBox>
              <Image
                src={"/images/info.png"}
                priority={true}
                fill
                alt="image"
                style={{
                  objectFit: "contain",
                }}
              />
            </ImageBox>
            <InfoBox>
              <Info>
                <Title>Name,</Title>
                <Content>Kim kyeong ill</Content>
              </Info>
              <Info>
                <Title>Part,</Title>
                <Content>FE &#91;Front-End Developer&#93;</Content>
              </Info>
              <Info>
                <Title>Edu,</Title>
                <Content>
                  2010.03 ~ 2016.03, Konkuk University &#40;Glocal&#41;
                  Graduation
                </Content>
              </Info>
              <Info>
                <Title>Major,</Title>
                <Content>Web developer</Content>
              </Info>
            </InfoBox>
          </ProfileBox>
          <EducationBox>
            <EducationTitle>Education activity.</EducationTitle>
            <GapBox>
              <FlexBox>
                <Date>2022.03 ~ 2022.12,</Date>
                <Content>스파르타코딩클럽 항해99 9기 수료</Content>
              </FlexBox>
              <FlexBox>
                <Date>2023.01 ~ 2023.01,</Date>
                <Content>&#91;개인&#93;포트폴리오 제작</Content>
              </FlexBox>
              <FlexBox>
                <Date>2023.01 ~ 2023.01,</Date>
                <Content>&#91;개인&#93;카카오 &#40;Kakao&#41; 제작</Content>
              </FlexBox>
              <FlexBox>
                <Date>2023.02 ~ 2023.02,</Date>
                <Content>&#91;개인&#93;F:E Func, Development 개발 중</Content>
              </FlexBox>
              <FlexBox>
                <Date>2023.02 ~ 2023.02,</Date>
                <Content>&#91;개인&#93;Next-js 포트폴리오 개발 중</Content>
              </FlexBox>
            </GapBox>

            <EducationTitle>Contact.</EducationTitle>
            <div>
              <FlexBox>
                <Date width={"100px"}>email,</Date>
                <Content>rla123dlf@gmail.com</Content>
              </FlexBox>
              <FlexBox>
                <Date width={"100px"}>github,</Date>
                <Click onClick={() => window.open("https://github.com/KKI147")}>
                  https://github.com/KKI147
                </Click>
              </FlexBox>
            </div>
          </EducationBox>
        </ContentLayout>
      </>
    </>
  );
}

const ContentLayout = styled.div`
  font-size: 1.5rem;
  color: #fff;
  @media (max-width: 1024px) {
    font-size: 1.2rem;
  }
`;

const ProfileBox = styled.div`
  display: flex;
  align-items: center;
`;

const ImageBox = styled.div`
  position: relative;
  width: 200px;
  height: 200px;
  @media (max-width: 1024px) {
    width: 180px;
    height: 180px;
  }
  @media (max-width: 640px) {
    width: 160px;
    height: 160px;
  }
  @media (max-width: 480px) {
    width: 140px;
    height: 140px;
  }
`;

const InfoBox = styled.div`
  width: 100%;
  padding: 15px 0 0 0;
  margin: 0 0 0 16px;
  @media (max-width: 1024px) {
    padding: 10px 0 0 0;
  }
  @media (max-width: 640px) {
    padding: 6px 0 0 0;
    margin: 0 0 0 10px;
  }
  @media (max-width: 480px) {
    padding: 2px 0 0 0;
    margin: 0 0 0 5px;
  }
`;

const Info = styled.div`
  display: flex;
  align-items: center;
  margin: 0px 15px 15px 15px;
  @media (max-width: 1024px) {
    margin: 0px 10px 10px 10px;
  }
  @media (max-width: 640px) {
    margin: 0px 6px 6px 6px;
  }
  @media (max-width: 480px) {
    margin: 0px 2px 2px 2px;
  }
`;

const Title = styled.div`
  font-size: 1.2rem;
  position: relative;
  width: 5%;
  margin: 0 72px 0 0;
  @media (max-width: 1024px) {
    font-size: 1.1rem;
    margin: 0 48px 0 0;
  }
  @media (max-width: 640px) {
    width: 9%;
    font-size: 1rem;
    margin: 0 36px 0 0;
  }
  @media (max-width: 480px) {
    width: 18px;
    font-size: 0.8rem;
    /* margin: 0 24px 0 0; */
  }
`;
const Content = styled.div`
  color: #8e8e8e;
  font-size: 1.1rem;
  @media (max-width: 1024px) {
    font-size: 1rem;
  }
  @media (max-width: 640px) {
    font-size: 0.8rem;
  }
  @media (max-width: 480px) {
    font-size: 0.6rem;
  }
`;

const EducationBox = styled.div`
  padding: 48px 0 35px 12px;
  @media (max-width: 1024px) {
    padding: 15px 0 35px 0;
  }
  @media (max-width: 480px) {
    text-align: center;
    padding: 28px 0 35px 0;
  }
`;

const FlexBox = styled.div`
  display: flex;
  align-items: center;
  margin: 20px 0;
`;
const EducationTitle = styled.div`
  font-size: 2rem;
  margin: 0 0 28px 0;
  font-weight: 600;
  @media (max-width: 1024px) {
    font-size: 1.5rem;
    margin: 0 0 22px 0;
  }
  @media (max-width: 640px) {
    font-size: 1.3rem;
    margin: 0 0 16px 0;
  }
  @media (max-width: 480px) {
    font-size: 1.1rem;
    margin: 0 0 10px 0;
  }
`;

const GapBox = styled.div`
  margin: 12px 0 50px 0;
`;

const Date = styled.div<CssProps>`
  width: ${(props) => props.width || "250px"};
  font-size: 1.2rem;
  @media (max-width: 1024px) {
    width: ${(props) => props.width || "200px"};
    font-size: 1.1rem;
  }
  @media (max-width: 640px) {
    width: ${(props) => props.width || "170px"};
    font-size: 1rem;
  }
  @media (max-width: 480px) {
    width: ${(props) => props.width || "150px"};
    font-size: 0.9rem;
  }
`;

const Click = styled.div`
  color: #8e8e8e;
  font-size: 1.2rem;
  cursor: pointer;

  @media (max-width: 1024px) {
    font-size: 1.1rem;
  }
  @media (max-width: 640px) {
    font-size: 1rem;
  }
  @media (max-width: 480px) {
    font-size: 0.9rem;
  }
`;
