import Head from "next/head";
import styled, { css } from "styled-components";
import Wrapper from "@/component/Wrapper";
import Image from "next/image";

interface CssProps {
  width: string;
}

export default function Education() {
  return (
    <>
      <Head>
        <title>Education</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <ContentLayout>
          <ProfileBox>
            <Image
              src={"/images/info.png"}
              width={180}
              height={180}
              alt="image"
              loading="lazy"
              style={{}}
            />
            <InfoBox>
              <Info>
                <Title>Name,</Title>
                <Content>Kim kyeong ill</Content>
              </Info>
              <Info>
                <Title>Part,</Title>
                <Content>FE{"{Front-End Developer}"}</Content>
              </Info>
              <Info>
                <Title>Edu,</Title>
                <Content>
                  2010.03 ~ 2016.03, Konkuk University(Glocal) Graduation
                </Content>
              </Info>
              <Info>
                <Title>Major,</Title>
                <Content>Web developer</Content>
              </Info>
            </InfoBox>
          </ProfileBox>
          <EducationBox>
            <EducationTitle>Education activity.</EducationTitle>
            <GapBox>
              <FlexBox>
                <Date>2022.03 ~ 2022.12,</Date>
                <Content>스파르타코딩클럽 항해99 9기 수료</Content>
              </FlexBox>
              <FlexBox>
                <Date>2023.01 ~ 2023.01,</Date>
                <Content>[개인]포트폴리오 제작</Content>
              </FlexBox>
              <FlexBox>
                <Date>2023.01 ~ 2023.01,</Date>
                <Content>[개인]카카오(Kakao) 제작</Content>
              </FlexBox>
              <FlexBox>
                <Date>2023.02 ~ 2023.02,</Date>
                <Content>[개인]F:E Func, Development 개발 중</Content>
              </FlexBox>
              <FlexBox>
                <Date>2023.02 ~ 2023.02,</Date>
                <Content>[개인]Next-js 포트폴리오 개발 중</Content>
              </FlexBox>
            </GapBox>

            <EducationTitle>Contact.</EducationTitle>
            <div>
              <FlexBox>
                <Date color="100px">email,</Date>
                <Content>rla123dlf@gmail.com</Content>
              </FlexBox>
              <FlexBox>
                <Date color="100px">github,</Date>
                <Click onClick={() => window.open("https://github.com/KKI147")}>
                  https://github.com/KKI147
                </Click>
              </FlexBox>
            </div>
          </EducationBox>
        </ContentLayout>
      </Wrapper>
    </>
  );
}

const ContentLayout = styled.div`
  font-size: 1.5rem;
  color: #fff;
`;

const ProfileBox = styled.div`
  display: flex;
  height: fit-content;
  align-items: center;
`;
const InfoBox = styled.div`
  margin: 0 0 0 16px;
`;

const Info = styled.div`
  display: flex;
  margin: 15px 15px;
`;

const Title = styled.div`
  width: 50px;
  margin: 0 72px 0 0;
`;
const Content = styled.div`
  color: #8e8e8e;
  font-size: 1.2rem;
`;

const EducationBox = styled.div`
  padding: 48px 0 35px 12px;
`;

const FlexBox = styled.div`
  display: flex;
  margin: 20px 0;
`;
const EducationTitle = styled.div`
  font-size: 2rem;
  margin: 0 0 28px 0;
  font-weight: 600;
`;

const GapBox = styled.div`
  margin: 12px 0 50px 0;
`;

const Date = styled.div`
  width: ${(props) => props.color || "250px"};
  font-size: 1.2rem;
`;

const Click = styled.div`
  color: #8e8e8e;
  font-size: 1.2rem;
  cursor: pointer;
`;
