import Head from "next/head";
import Image from "next/image";

import styles from "@/styles/Home.module.css";

import styled from "styled-components";

import Layout from "./../component/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  );
}
