import Head from "next/head";
import styled, { css, keyframes } from "styled-components";

import Image from "next/image";

interface CssType {
  variant: string;
}
export default function Skils() {
  return (
    <>
      <Head>
        <title>SKils</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <ContentLayout>
          <LineBox>
            <Line></Line>
            <div>Front-end(FE)</div>
          </LineBox>

          <Box>
            <ImageBox>
              <Image
                src={"/images/html.png"}
                alt="image"
                loading="lazy"
                width={64}
                height={64}
                style={{
                  position: "absolute",
                  top: "50%",
                  left: "50%",
                  transform: "translate(-50%, -50%)",
                  width: "65%",
                  height: "65%",
                }}
              />
            </ImageBox>
            <ContentBox>
              <FlexBox variant="common">
                <Title>Name,</Title>
                <Content>HTML 5</Content>
              </FlexBox>
              <FlexBox variant="common">
                <Title>Proficiency,</Title>
                <Graph>
                  <Animation variant="html" />
                  <Text>65%</Text>
                </Graph>
              </FlexBox>
              <FlexBox variant="summary">
                <Title>Summary,</Title>
                <Content>
                  <ContentText>
                    <div>
                      - Dom의 구조와 Web에 어떻게 렌더링이 되는지 이해하고
                      있습니다.
                    </div>
                    <div>
                      - HTTP Method를 통해 비동기 통신을 구현할 수 있습니다.
                    </div>
                    <div>
                      - TAG 와 MetaTAG및 SEO에 대한 필요성을 이해하고 있습니다.
                    </div>
                  </ContentText>
                </Content>
              </FlexBox>
            </ContentBox>
          </Box>
          <Box>
            <ImageBox>
              <Image
                src={"/images/css.png"}
                width={64}
                height={64}
                alt="image"
                loading="lazy"
                style={{
                  position: "absolute",
                  top: "50%",
                  left: "50%",
                  transform: "translate(-50%, -50%)",
                  width: "65%",
                  height: "65%",
                }}
              />
            </ImageBox>
            <ContentBox>
              <FlexBox variant="common">
                <Title>Name,</Title>
                <Content>CSS 3</Content>
              </FlexBox>
              <FlexBox variant="common">
                <Title>Proficiency,</Title>
                <Graph>
                  <Animation variant="html" />
                  <Text>65%</Text>
                </Graph>
              </FlexBox>
              <FlexBox variant="summary">
                <Title>Summary,</Title>
                <Content>
                  <ContentText>
                    <div>
                      - 디자이너님과 협업하여 CSS Publishing 경험이 있습니다.
                    </div>
                    <div>
                      - Media Query를 사용하여 반응형 웹을 만들어본 경험이
                      있습니다.
                    </div>
                    <div>
                      - Props와 Switch문을 활용하여 전역으로 Css값을 사용할 수
                      있습니다.
                    </div>
                  </ContentText>
                </Content>
              </FlexBox>
            </ContentBox>
          </Box>
          <Box>
            <ImageBox>
              <Image
                src={"/images/javascript.png"}
                width={64}
                height={64}
                alt="image"
                loading="lazy"
                style={{
                  position: "absolute",
                  top: "50%",
                  left: "50%",
                  transform: "translate(-50%, -50%)",
                  width: "65%",
                  height: "65%",
                }}
              />
            </ImageBox>
            <ContentBox>
              <FlexBox variant="common">
                <Title>Name,</Title>
                <Content>JavaScript</Content>
              </FlexBox>
              <FlexBox variant="common">
                <Title>Proficiency,</Title>
                <Graph>
                  <Animation variant="html" />
                  <Text>65%</Text>
                </Graph>
              </FlexBox>
              <FlexBox variant="summary">
                <Title>Summary,</Title>
                <Content>
                  <ContentText>
                    <div>
                      - Javascript의 기초적인 변수, 형변환, 연산자, 함수등을
                      다룰수 있습니다.
                    </div>
                    <div>
                      - 변수선언 차이점, 화살표 함수, 구조 분해 할당등 Es6문법을
                      이해하고 다룰수 있습니다.
                    </div>
                  </ContentText>
                </Content>
              </FlexBox>
            </ContentBox>
          </Box>
          <Box>
            <ImageBox>
              <Image
                src={"/images/react.png"}
                width={64}
                height={64}
                alt="image"
                loading="lazy"
                style={{
                  position: "absolute",
                  top: "50%",
                  left: "50%",
                  transform: "translate(-50%, -50%)",
                  width: "65%",
                  height: "65%",
                }}
              />
            </ImageBox>
            <ContentBox>
              <FlexBox variant="common">
                <Title>Name,</Title>
                <Content>React</Content>
              </FlexBox>
              <FlexBox variant="common">
                <Title>Proficiency,</Title>
                <Graph>
                  <Animation variant="react" />
                  <Text>60%</Text>
                </Graph>
              </FlexBox>
              <FlexBox variant="summary">
                <Title>Summary,</Title>
                <Content>
                  <Content>
                    <ContentText>
                      <div>- React의 render 과정을 이해하고 있습니다.</div>
                      <div>
                        - React의 Life Cycle을 이해하고 있으며 useState,
                        useEffect같은 hook을 사용할수 있습니다.
                      </div>
                    </ContentText>
                  </Content>
                </Content>
              </FlexBox>
            </ContentBox>
          </Box>
          <Box>
            <ImageBox>
              <Image
                src={"/images/typescript.png"}
                width={64}
                height={64}
                alt="image"
                loading="lazy"
                style={{
                  position: "absolute",
                  top: "50%",
                  left: "50%",
                  transform: "translate(-50%, -50%)",
                  width: "65%",
                  height: "65%",
                }}
              />
            </ImageBox>
            <ContentBox>
              <FlexBox variant="common">
                <Title>Name,</Title>
                <Content>TypeScript</Content>
              </FlexBox>
              <FlexBox variant="common">
                <Title>Proficiency,</Title>
                <Graph>
                  <Animation variant="ts" />
                  <Text>55%</Text>
                </Graph>
              </FlexBox>
              <FlexBox variant="summary">
                <Title>Summary,</Title>
                <Content>
                  <ContentText>
                    <div>
                      - TypeScript의 필요성에 대해 이해하고 있으며 기초적인
                      타입을 지정할 수 있습니다..
                    </div>
                    <div>
                      - 다양한 프로젝트를 만들면서 꾸준히 학습중 입니다.
                    </div>
                  </ContentText>
                </Content>
              </FlexBox>
            </ContentBox>
          </Box>
          <Box>
            <ImageBox>
              <Image
                src={"/images/next.png"}
                width={64}
                height={64}
                alt="image"
                loading="lazy"
                style={{
                  position: "absolute",
                  top: "50%",
                  left: "50%",
                  transform: "translate(-50%, -50%)",
                  width: "65%",
                  height: "65%",
                }}
              />
            </ImageBox>
            <ContentBox>
              <FlexBox variant="common">
                <Title>Name,</Title>
                <Content>Next-JS</Content>
              </FlexBox>
              <FlexBox variant="common">
                <Title>Proficiency,</Title>
                <Graph>
                  <Animation variant="ts" />
                  <Text>55%</Text>
                </Graph>
              </FlexBox>
              <FlexBox variant="summary">
                <Title>Summary,</Title>
                <Content>
                  <ContentText>
                    <div>
                      - React와 Next-JS의 차이점을 이해하고 SSR, SEO,
                      TypeScript와 접목해서 다룰수 있습니다.
                    </div>
                    <div>
                      - 다양한 프로젝트를 만들면서 꾸준히 학습중 입니다.
                    </div>
                  </ContentText>
                </Content>
              </FlexBox>
            </ContentBox>
          </Box>
        </ContentLayout>
      </>
    </>
  );
}

const ContentLayout = styled.div`
  font-size: 2rem;
  color: #fff;
  @media (max-width: 1024px) {
    font-size: 1.8rem;
  }
  @media (max-width: 640px) {
    font-size: 1.6rem;
  }
  @media (max-width: 480px) {
    font-size: 1.4rem;
  }
`;
const LineBox = styled.div`
  display: flex;
`;
const Line = styled.div`
  width: 4px;
  height: 33px;
  margin: 0 10px 0 0;
  background-color: #fff;
  @media (max-width: 1024px) {
    height: 28px;
  }
  @media (max-width: 640px) {
    height: 24px;
  }
  @media (max-width: 480px) {
    width: 2px;
    height: 20px;
  }
`;
const Box = styled.div`
  display: flex;
  margin: 24px 0;
`;

const ImageBox = styled.div`
  position: relative;
  width: 100px;
  height: 100px;
  border-radius: 16px;
  background-color: #fff;
  @media (max-width: 1024px) {
    width: 90px;
    height: 90px;
    margin: 2px 0 0 0;
  }
  @media (max-width: 640px) {
    width: 80px;
    height: 80px;
    margin: 4px 0 0 0;
  }
  @media (max-width: 480px) {
    width: 70px;
    height: 70px;
    margin: 2px 0 0 0;
  }
`;

const ContentBox = styled.div`
  position: relative;
  width: 80%;
  /* width: calc(100% - 130px); */
  margin: 0 0 0 30px;
  @media (max-width: 1024px) {
    margin: 0 0 0 25px;
  }
  @media (max-width: 640px) {
    width: calc(100% - 100px);
    margin: 0 0 0 15px;
  }
  @media (max-width: 480px) {
    margin: 0 0 0 10px;
  }
`;

const FlexBox = styled.div`
  display: flex;
  width: 100%;
  margin: 10px 0 0 0;
  @media (max-width: 1024px) {
    margin: 8px 0 0 0;
  }
  @media (max-width: 640px) {
  }
  @media (max-width: 480px) {
    margin: 6px 0 0 0;
  }
  ${({ variant }: CssType) => {
    switch (variant) {
      case "common":
        return css`
          align-items: center;
        `;
      case "summary":
        return css`
          align-items: start;
        `;

      default:
        break;
    }
  }}
`;

const Title = styled.div`
  position: relative;
  width: 20%;
  /* width: calc(25% - 10px); */
  margin: 0 10px 0 0;
  font-size: 1.2rem;
  @media (max-width: 1024px) {
    font-size: 1.1rem;
    /* width: 100px; */
  }
  @media (max-width: 640px) {
    width: 22%;
    font-size: 1rem;
    margin: 0 20px 0 0;
  }
  @media (max-width: 480px) {
    font-size: 0.9rem;
  }
`;

const Content = styled.div`
  /* width: 70%; */
  color: #8e8e8e;
  font-size: 1rem;
  word-break: keep-all;
  @media (max-width: 1024px) {
    width: 70%;
    font-size: 0.9rem;
  }
  @media (max-width: 640px) {
    font-size: 0.8rem;
  }
  @media (max-width: 480px) {
    font-size: 0.7rem;
  }
`;

const ContentText = styled.div`
  margin: 5px 0;
  line-height: 1.5;
`;
const HtmlEffect = keyframes`
0% {
  width: 0px;
      background-color: #888888;
}
100% {
  width: 65%;
      background-color: #ffa877;
}
`;

const ReactEffect = keyframes`
0% {
  width: 0px;
      background-color: #888888;
}
100% {
  width: 60%;
      background-color: #ffa877;
}
`;

const TsEffect = keyframes`
0% {
  width: 0px;
      background-color: #888888;
}
100% {
  width: 55%;
      background-color: #ffa877;
}
`;

const Animation = styled.div`
  position: absolute;
  height: 100%;
  border-radius: 24px;
  background-color: #ffa877;
  z-index: 2;
  ${({ variant }: CssType) => {
    switch (variant) {
      case "html":
        return css`
          width: 65%;
          animation: ${HtmlEffect} 2s;
        `;
      case "react":
        return css`
          width: 60%;
          animation: ${ReactEffect} 2s;
        `;
      case "ts":
        return css`
          width: 55%;
          animation: ${TsEffect} 2s;
        `;
      default:
        break;
    }
  }}
`;

const Graph = styled.div`
  position: relative;
  width: 65%;
  height: 21px;
  text-align: center;
  /* font-size: 1rem; */
  border-radius: 24px;
  background-color: #888888;
  @media (max-width: 1024px) {
    /* font-size: 0.9rem; */
    width: 70%;
    height: 20px;
  }
  @media (max-width: 640px) {
    width: 70%;
    height: 18px;
  }
  @media (max-width: 480px) {
    height: 16px;
  }
`;

const Text = styled.div`
  position: absolute;
  right: 5%;
  color: #fff;
  font-size: 0.8rem;
  padding: 2.5px 0;
  z-index: 5;
  @media (max-width: 1024px) {
    font-size: 0.7rem;
    padding: 4px 0;
  }
  @media (max-width: 640px) {
    font-size: 0.6rem;
    padding: 3px 0;
  }
  @media (max-width: 480px) {
    font-size: 0.5rem;
    padding: 2px 0;
  }
`;
